name: Build iOS IPA

on:
  workflow_dispatch: 

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate iOS Folder (Magic Fix for Windows)
        run: |
          rm -rf ios
          flutter create . --platforms ios

      - name: Set iOS Version to 15.0 for Firebase
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/^# platform :ios.*/platform :ios, '15.0'/" ios/Podfile

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (Unsigned)
        run: flutter build ios --release --no-codesign

      - name: Create IPA file
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qq -r app.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qimmah-Lab-iOS
          path: app.ipa